[tool.yapf]
based_on_style = "pep8"
indent_width = 2
column_limit = 120
continuation_indent_width = 2
split_before_first_argument = false
align_closing_bracket_with_visual_indent = true
dedent_closing_brackets = false