repos:
  - repo: local
    hooks:
      - id: python-tests
        name: Run Python Tests
        entry: bash -c 'cd tools/annotation && export PYTHONPATH=/workspace/tools/annotation:$PYTHONPATH && python3 -m pytest tests/ --tb=short -x'
        language: system
        files: \.(py)$
        pass_filenames: false
      
      - id: python-syntax-check
        name: Python Syntax Check
        entry: python3 -m py_compile
        language: system
        files: \.(py)$
        
      - id: python-import-check
        name: Python Import Check
        entry: bash -c 'cd tools/annotation && export PYTHONPATH=/workspace/tools/annotation:$PYTHONPATH && python3 -c "import sys; [__import__(f.replace(\"/\", \".\").replace(\".py\", \"\")) for f in sys.argv[1:] if not f.startswith(\"tests/\")]"'
        language: system
        files: \.(py)$
        exclude: ^tests/
        pass_filenames: true

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: [--line-length=120]
        files: tools/annotation/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120, --extend-ignore=E203,W503]
        files: tools/annotation/.*\.py$
