# Server Configuration
server:
  host: "0.0.0.0"
  port: 8080
  websocket_port: 8081
  
emulator:
  name: "BlueStacks"
  adb_port: 5555
  resolution: "1280x720"
  dpi: 240
  headless: true
  
vision:
  capture_fps: 30
  preprocessing:
    resize: [224, 224]
    normalize: true
    grayscale: false
    
ml:
  device: "cuda"
  batch_size: 32
  learning_rate: 0.0003
  
logging:
  level: "INFO"
  file: "data/logs/server.log"
  
storage:
  replay_buffer_size: 100000
  model_save_interval: 1000
  checkpoint_dir: "data/models/"
